description = "Examples for Ada Security Library"
name = "security_samples"
version = "1.5.2"
licenses = "Apache-2.0"
maintainers = ["Stephane.Carrez@gmail.com"]
maintainers-logins = ["stcarrez"]
authors = ["Stephane.Carrez@gmail.com"]
project-files = ["samples.gpr"]
tags = ["security", "oauth2", "authentication", "permissions", "jwt"]
website = "https://gitlab.com/stcarrez/ada-security"
long-description = """

Examples for Ada Security

"""

[[depends-on]]
security = "*"
utilada = "*"
utilada_aws = "*"
aws = "^24.0"

[configuration]
disabled = true

[[pins]]
security = { path = '..' }
